apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argodeploy
  name: argodeploy
  namespace: -petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argodeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argodeploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
