apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argodeploy
  name: argodeploy
  namespace: petclinic
spec:
  containers:
  - command:
    - /bin/sh
    - sleep
    - "3600"
    image: nginx
    name: argodeploy
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
